### ISSUE TITLE
Question -  have you seen the chef-ssh-hardening cookbook?

### ISSUE THREAD

**Issue by iennae** [route1337/chef-cookbook-sshconfig#3]
I noticed that you had some configuration to harden ssh, and wondered if you had seen https://github.com/dev-sec/chef-ssh-hardening? I'm wondering whether collaborating together to make a really awesome hardened ssh client/server would be useful or not?

**Comment by ahrenstein** [comment]
Hello @iennae. I haven't seen it before but I will be sure to clone it and check it out soon. I'd definitely be interested in collaboration for making a really awesome hardened configuration.
